# Generated by Django 5.0.4 on 2024-06-11 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0002_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
